Update rclone-sync script
- Use default rclone filtering features instead of custom logic
- Currently unusable do to unmaintained rclone proton drive support

diff --git a/rclone-sync b/rclone-sync
--- a/rclone-sync
+++ b/rclone-sync
@@ -1,30 +1,85 @@
 #!/usr/bin/env bash
 
-#Define variables
-exclude_file_path="${XDG_CONFIG_HOME:=$HOME/.config}/rclone/rclone-exclude.txt"
-remote="Proton"
+CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/rclone-sync"
+FILTER_FILE="${XDG_CONFIG_HOME:=$HOME/.config}/rclone-sync/filters"
+REMOTE="proton"
+SOURCE="${HOME}"
 
-# Check if rclone is installed
-if ! command -v rclone > /dev/null; then
-  echo "Rclone package missing"
-  exit
-fi
+log() {
+  local flag="$1"
+  local message="$2"
 
-#Check if remote has been configured
-if ! grep -q "$remote" <<< "$(rclone listremotes 2>&1)"; then
-  echo "Remote $remote hasn't been configured yet"
-  exit
-fi
+  if command -v notify-send >/dev/null 2>&1; then
+    if [[ "${flag}" == '1' ]]; then
+      notify-send --urgency normal 'Rclone Sync' "${message}"
+    elif [[ "${flag}" == '2' ]]; then
+      notify-send --urgency critical 'Rclone Sync' "${message}"
+    fi
+  fi
 
-# Check existance of exclude_file
-[ ! -f "$exclude_file_path" ] && touch "$exclude_file_path" && echo "Warning: Empty exclude file!"
+  echo "$message"
+}
 
-#Create packages backups
-if ! packages-backup; then
-  echo "ERROR: Unable to run packages-backup"
-fi
+inf() { log '1' "INFO: $*"; }
+warn() { log '1' "WARN: $*" >&2; }
+err() { log '2' "ERROR: $*" >&2; }
 
-# Sync files to Proton Drive
-rclone sync ~/Documents --exclude-from "$exclude_file_path" "$remote":'Documents' -vv
-rclone sync ~/Backups --exclude-from "$exclude_file_path" "$remote":'Backups' -vv
-rclone sync ~/Dotfiles --exclude ".git/**" "$remote":'Dotfiles' -vv
+check_expected_dirs() {
+  local expected_dirs="${CONF_DIR}/expected_dirs"
+
+  if [[ -f "${expected_dirs}" ]]; then
+
+    while IFS= read -r line; do
+      local directory=${line//[[:space:]]/}
+
+      if [[ -z ${directory} ]]; then
+        continue
+      fi
+
+      if [[ ! -d "${directory}" ]]; then
+        err "Expected directory ${directory} doesn't exists."
+        return 1
+      fi
+    done <"${expected_dirs}"
+
+  fi
+}
+
+check_rclone_setup() {
+  if ! command -v rclone >/dev/null; then
+    err "Rclone package missing"
+    return 1
+  fi
+
+  if ! grep --quiet "${REMOTE}" <<<"$(rclone listremotes)"; then
+    err "Remote ${REMOTE} hasn't been configured yet"
+    return 1
+  fi
+
+  if [[ ! -f "${FILTER_FILE}" ]]; then
+    err "No filter file found at ${FILTER_FILE}"
+    return 1
+  fi
+}
+
+main() {
+  if ! check_rclone_setup; then
+    exit 1
+  fi
+
+  if ! check_expected_dirs; then
+    exit 1
+  fi
+
+  if ! packages-backup; then
+    warn "Failed to run packages-backup, skipping"
+  fi
+
+  inf "Starting Rclone sync"
+
+  if rclone sync --check-first --log-level INFO --filter-from "${FILTER_FILE}" "${SOURCE}" "${REMOTE}:"; then
+    inf "Rclone sync finished succesfully"
+  fi
+}
+
+main
